version: '3'
services:

  postgresql:
    container_name: habita-database
    image: postgres:14.8
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
volumes:
  habita-volume: